### ISSUE TITLE
How could we compare the corrected perturbation data with the raw reference data?

### ISSUE THREAD

**Issue by caodudu** [vandijklab/CINEMA-OT#14]
Hi!
Thanks for your excellent framework! I have tried to follow the official tutorial (https://github.com/vandijklab/CINEMA-OT/blob/main/cinemaot_tutorial.ipynb) and I found the main output are `cf`,  `ot` and  `de`.  It appears to me that `de` is the corrected adata which only corresponds to perturbation.  So, How could we compare the corrected perturbation data with the raw reference data? The downstream DE analysis (t test) in the tutorial seems to be performed within perturbation data. Could you provide some suggestions if I wanna to perform DE analysis on the corrected data between perturbation and reference?
After the ICA step, could optimal transport generate the match matrix `refer x refer` besides the matirx `refer x perturbation`?
Best regards
cdd

**Comment by MingzeDong** [comment]
The output de corresponds to the single-cell treatment effect matrix for the treated cells. It already includes the comparison between perturbation and control data. The downstream DE analysis may be conducted directly for de using t-test or wilcoxon between values in de.X and 0, potentially with some thresholding of the effect size.
For the second point, the matching matrix of shape refer times refer is not generated because it is not helpful for estimating the treatment effect across experiments.

Hopefully this helps!
