### ISSUE TITLE
Is it possible to apply CINEMA-OT to Spatial-seq Data?

### ISSUE THREAD

**Issue by Lixinyoung** [vandijklab/CINEMA-OT#8]
Hello,

Very intriguing tools. I wonder can CINEMA-OT be applied to Spatial-seq data such as sequence-based Visium or FISH-based Xenium?

Thank you.

**Comment by MingzeDong** [comment]
Thank you! In principle, CINEMA-OT can be used to compare spatial datasets with different conditions. But here are a few things to keep in mind:
1. Whether to use spatial information. CINEMA-OT starts from an initialized embedding (by default PCA) and then computes confounder matching. The PCA itself does not use spatial information. Therefore, it may only match cells with "correct transcriptome profiles" instead of cells from "corresponding spatial locations". This can be fixed by using spatial-aware dimensional reduction embeddings.
2. What is the quantity of interest. In spatial datasets, apart from differences across datasets, one source of "effect" can come from spatial interactions (e.g. a cell with its neighborhood). Therefore, the treatment effect computed from CINEMA-OT can contain two parts: 1. difference due to dataset condition; 2. difference due to different neighborhood interaction. Therefore the results would need more careful interpretation.
